# Generated by Django 3.2.6 on 2021-08-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='camera',
            field=models.BooleanField(default=True, verbose_name='Камера'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='charge_via_usb_type_c',
            field=models.BooleanField(default=True, verbose_name='Зарядка ноутбука через USB Type C'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='discrete_graphics',
            field=models.BooleanField(default=True, verbose_name='Дискретная видеокарта'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='fast_charging',
            field=models.BooleanField(default=True, verbose_name='Быстрая зарядка'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='multimedia_touchpad',
            field=models.BooleanField(default=True, verbose_name='Мультимедийная сенсорная панель'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='usb_c_power_adapter',
            field=models.BooleanField(default=True, verbose_name='Адаптер питания USB Type C'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='accelerometer',
            field=models.BooleanField(default=True, verbose_name='Акселерометр'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='ant',
            field=models.BooleanField(default=True, verbose_name='ANT+'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='auto_focus',
            field=models.BooleanField(default=True, verbose_name='Автоматическая фокусировка'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='barometer',
            field=models.BooleanField(default=True, verbose_name='Барометр'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='beidou',
            field=models.BooleanField(default=True, verbose_name='Beidou'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='built_in_camera',
            field=models.BooleanField(default=True, verbose_name='Встроенная камера'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='built_in_flash',
            field=models.BooleanField(default=True, verbose_name='Встроенная вспышка'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='diaphragm',
            field=models.BooleanField(default=True, verbose_name='Диафрагма'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='dual_camera',
            field=models.BooleanField(default=True, verbose_name='Двойная камера'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='dust_moisture_protection',
            field=models.BooleanField(default=True, verbose_name='Пыле-влагозащита'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='edge',
            field=models.BooleanField(default=True, verbose_name='Передача данных EDGE'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='face_or_iris_map_scanner',
            field=models.BooleanField(default=True, verbose_name='Сканер карты лица или радужки глаза'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='face_unlock',
            field=models.BooleanField(default=True, verbose_name='Разблоктровка по лицу'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='fast_charging',
            field=models.BooleanField(default=True, verbose_name='Быстрая зарядка'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='fingerprint_scanner',
            field=models.BooleanField(default=True, verbose_name='Сканер отпечатка пальца'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='five_g',
            field=models.BooleanField(default=True, verbose_name='5G'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='fm_receiver',
            field=models.BooleanField(default=True, verbose_name='FM-приемник'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='glonass',
            field=models.BooleanField(default=True, verbose_name='GLONASS'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='gps',
            field=models.BooleanField(default=True, verbose_name='GPS'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='gyroscope',
            field=models.BooleanField(default=True, verbose_name='Гидроскоп'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='hdmi',
            field=models.BooleanField(default=True, verbose_name='HDMI-выход'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='heart_rate_monitor',
            field=models.BooleanField(default=True, verbose_name='Монитор сердечного ритма'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='hspa',
            field=models.BooleanField(default=True, verbose_name='HSPA'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='hspa_plus',
            field=models.BooleanField(default=True, verbose_name='HSPA+'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='ir_transmitter',
            field=models.BooleanField(default=True, verbose_name='ИК-передатчик'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='led_indicator',
            field=models.BooleanField(default=True, verbose_name='Светодиодный индикатор'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='light_sensor',
            field=models.BooleanField(default=True, verbose_name='Датчик освещенности'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='lte',
            field=models.BooleanField(default=True, verbose_name='LTE'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='nfs',
            field=models.BooleanField(default=True, verbose_name='NFS'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='non_removable',
            field=models.BooleanField(default=True, verbose_name='Несъемный аккумулятор'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='optical_stabilization',
            field=models.BooleanField(default=True, verbose_name='Оптическая стабилизация'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='physical_qwerty_keyboard',
            field=models.BooleanField(default=True, verbose_name='Физическая QWERTY-клавиатура'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='registering_the_force_of_pressing',
            field=models.BooleanField(default=True, verbose_name='Регистрация силы нажатий'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='replaceable_panels',
            field=models.BooleanField(default=True, verbose_name='Съёмные панели'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='shockproof_housing',
            field=models.BooleanField(default=True, verbose_name='Ударопрочный корпус'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='stereo_speakers',
            field=models.BooleanField(default=True, verbose_name='Стереодинамики'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='touch_screen',
            field=models.BooleanField(default=True, verbose_name='Сенсорный экран'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='wireless_charging',
            field=models.BooleanField(default=True, verbose_name='Беспроводная зарядка'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='work_with_gloves',
            field=models.BooleanField(default=True, verbose_name='Работа в перчатках'),
        ),
    ]
