# Generated by Django 3.2.6 on 2021-08-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storeapp', '0002_auto_20210819_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=20, verbose_name='Описание')),
                ('icon_image', models.ImageField(upload_to='web_media/tab_icons', verbose_name='Иконки svg-формат')),
            ],
            options={
                'verbose_name': 'Дополнительная информация',
            },
        ),
    ]
