# Generated by Django 3.2.6 on 2021-09-13 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Storeapp', '0006_auto_20210908_0142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notebooktranslation',
            options={'verbose_name': 'Ноутбуки перевод ru - en', 'verbose_name_plural': 'Ноутбуки переводы ru - en'},
        ),
        migrations.AlterModelOptions(
            name='smartphonetranslation',
            options={'verbose_name': 'Смартфоны перевод ru - en', 'verbose_name_plural': 'Смартфоны переводы ru - en'},
        ),
        migrations.AlterModelOptions(
            name='videocards',
            options={'verbose_name': 'Видеокарта', 'verbose_name_plural': 'Видеокарты'},
        ),
        migrations.RemoveField(
            model_name='case',
            name='case_color',
        ),
        migrations.RemoveField(
            model_name='case',
            name='case_material',
        ),
        migrations.RemoveField(
            model_name='case',
            name='compatible_motherboard',
        ),
        migrations.RemoveField(
            model_name='case',
            name='cooler_illumination_color',
        ),
        migrations.RemoveField(
            model_name='case',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='case',
            name='expansion_slots',
        ),
        migrations.RemoveField(
            model_name='case',
            name='height',
        ),
        migrations.RemoveField(
            model_name='case',
            name='installed_coolers',
        ),
        migrations.RemoveField(
            model_name='case',
            name='max_cpu_cooler_height',
        ),
        migrations.RemoveField(
            model_name='case',
            name='max_motherboard_size',
        ),
        migrations.RemoveField(
            model_name='case',
            name='max_video_card_length',
        ),
        migrations.RemoveField(
            model_name='case',
            name='number_of_places_for_fans',
        ),
        migrations.RemoveField(
            model_name='case',
            name='power_supply',
        ),
        migrations.RemoveField(
            model_name='case',
            name='power_supply_loc',
        ),
        migrations.RemoveField(
            model_name='case',
            name='type_of_case',
        ),
        migrations.RemoveField(
            model_name='case',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='case',
            name='width',
        ),
        migrations.RemoveField(
            model_name='case',
            name='window_material',
        ),
        migrations.RemoveField(
            model_name='coolers',
            name='bearing',
        ),
        migrations.RemoveField(
            model_name='coolers',
            name='connection_type',
        ),
        migrations.RemoveField(
            model_name='coolers',
            name='cooling_type',
        ),
        migrations.RemoveField(
            model_name='coolers',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='coolers',
            name='fan_diameter',
        ),
        migrations.RemoveField(
            model_name='coolers',
            name='height',
        ),
        migrations.RemoveField(
            model_name='coolers',
            name='max_rotation_speed',
        ),
        migrations.RemoveField(
            model_name='coolers',
            name='noise_lvl',
        ),
        migrations.RemoveField(
            model_name='coolers',
            name='power_dissipation',
        ),
        migrations.RemoveField(
            model_name='coolers',
            name='radiator_metal',
        ),
        migrations.RemoveField(
            model_name='coolers',
            name='socket',
        ),
        migrations.RemoveField(
            model_name='coolers',
            name='total_fans',
        ),
        migrations.RemoveField(
            model_name='coolers',
            name='total_heat_pipes',
        ),
        migrations.RemoveField(
            model_name='coolers',
            name='type',
        ),
        migrations.RemoveField(
            model_name='coolers',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='coolers',
            name='width',
        ),
        migrations.RemoveField(
            model_name='hdd',
            name='buffer',
        ),
        migrations.RemoveField(
            model_name='hdd',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='hdd',
            name='drive_type',
        ),
        migrations.RemoveField(
            model_name='hdd',
            name='form_factor',
        ),
        migrations.RemoveField(
            model_name='hdd',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='hdd',
            name='power_consumption_1',
        ),
        migrations.RemoveField(
            model_name='hdd',
            name='power_consumption_2',
        ),
        migrations.RemoveField(
            model_name='hdd',
            name='sector_size',
        ),
        migrations.RemoveField(
            model_name='hdd',
            name='spindle_speed',
        ),
        migrations.RemoveField(
            model_name='hdd',
            name='thickness',
        ),
        migrations.RemoveField(
            model_name='hdd',
            name='time_between_failures',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='built_in_sound_type',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='chipset',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='form_factor',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='market_launch_date',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='max_memory',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='max_memory_frequency',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='memory_mode',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='memory_type',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='number_of_memory_slots',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='processor_support',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='raid_info',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='socket',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='sound_scheme',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='total_12v_lighting_connectors',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='total_5v_argb_lighting_connectors',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='total_audio_jack',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='total_case_fan_connectors',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='total_cpu_fan_connectors',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='total_hdmi',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='total_m2',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='total_pcl_express_2_x1',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='total_pcl_express_2_x16',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='total_pcl_express_2_x4',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='total_pcl_express_2_x8',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='total_pcl_express_x1',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='total_pcl_express_x16',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='total_ps_2',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='total_sata_3',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='total_sockets_for_cbo_processor',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='total_usb_2',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='total_usb_3_gen1_type_a_5gbit',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='total_usb_3_gen1_type_c_5gbit',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='total_usb_3_gen2_type_a_10gbit',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='total_usb_3_gen2_type_c_10gbit',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='ver_pcl_express',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='audio_outputs',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='bluetooth',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='built_in_microphone',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='built_in_speakers',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='clock_frequency_cpu',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='configuration_drive_type',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='cpu_power_consumption',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='drive_capacity',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='energy_reserve',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='free_memory_slots',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='graphics_card_feature',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='hdmi',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='lan',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='local_video_memory',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='matrix_frequency',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='max_ram_memory',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='mini_display_port',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='number_of_cores_cpu',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='number_of_ssd_slots',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='number_of_threads_cpu',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='ram_frequency',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='ram_memory',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='screen_diagonal',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='screen_resolution',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='thickness',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='total_usb_2',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='total_usb_type_a',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='total_usb_type_c',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='turbo_frequency_cpu',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='usb_4',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='vga',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='width',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='wifi',
        ),
        migrations.RemoveField(
            model_name='powersupplies',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='powersupplies',
            name='combined_load_12v',
        ),
        migrations.RemoveField(
            model_name='powersupplies',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='powersupplies',
            name='efficiency',
        ),
        migrations.RemoveField(
            model_name='powersupplies',
            name='height',
        ),
        migrations.RemoveField(
            model_name='powersupplies',
            name='max_line_current_12v',
        ),
        migrations.RemoveField(
            model_name='powersupplies',
            name='motherboard_power',
        ),
        migrations.RemoveField(
            model_name='powersupplies',
            name='number_of_separate_lines_12v',
        ),
        migrations.RemoveField(
            model_name='powersupplies',
            name='power',
        ),
        migrations.RemoveField(
            model_name='powersupplies',
            name='power_cable_length',
        ),
        migrations.RemoveField(
            model_name='powersupplies',
            name='power_supply_fan_size',
        ),
        migrations.RemoveField(
            model_name='powersupplies',
            name='power_supply_standard',
        ),
        migrations.RemoveField(
            model_name='powersupplies',
            name='total_fans',
        ),
        migrations.RemoveField(
            model_name='powersupplies',
            name='width',
        ),
        migrations.RemoveField(
            model_name='processors',
            name='base_clock_frequency',
        ),
        migrations.RemoveField(
            model_name='processors',
            name='cash_l2',
        ),
        migrations.RemoveField(
            model_name='processors',
            name='cash_l3',
        ),
        migrations.RemoveField(
            model_name='processors',
            name='crystal_code_name',
        ),
        migrations.RemoveField(
            model_name='processors',
            name='delivery_type',
        ),
        migrations.RemoveField(
            model_name='processors',
            name='market_launch_date',
        ),
        migrations.RemoveField(
            model_name='processors',
            name='max_frequency',
        ),
        migrations.RemoveField(
            model_name='processors',
            name='max_memory_frequency',
        ),
        migrations.RemoveField(
            model_name='processors',
            name='maximum_number_of_threads',
        ),
        migrations.RemoveField(
            model_name='processors',
            name='memory_support',
        ),
        migrations.RemoveField(
            model_name='processors',
            name='number_of_cores',
        ),
        migrations.RemoveField(
            model_name='processors',
            name='number_of_memory_channels',
        ),
        migrations.RemoveField(
            model_name='processors',
            name='socket',
        ),
        migrations.RemoveField(
            model_name='processors',
            name='tdp',
        ),
        migrations.RemoveField(
            model_name='processors',
            name='technical_process',
        ),
        migrations.RemoveField(
            model_name='processors',
            name='the_lineup',
        ),
        migrations.RemoveField(
            model_name='processors',
            name='type_gpu_express_controller',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='capacity_of_micro',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='cas_latency',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='chip_location',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='color',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='kit',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='micro_type',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='number_of_micro',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='number_of_ranks',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='pc_index',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='supply_voltage',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='timings',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='type',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='battery_capacity',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='built_in_camera',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='cpu_clock_speed',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='cpu_size',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='flash_memory',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='front_camera',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='gpu_frequency',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='length',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='max_frames_per_second',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='max_video_resolution',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='num_of_cores',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='num_of_main_cam',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='num_of_matrix_points',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='num_of_screen_colors',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='num_of_sim_cards',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='ram_mobile',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='refresh_rate',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='screen_res',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='screen_resolution_mobile',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='screen_size',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='technical_process',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='thickness',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='width',
        ),
        migrations.RemoveField(
            model_name='ssd',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='ssd',
            name='chip_type_flash',
        ),
        migrations.RemoveField(
            model_name='ssd',
            name='form_factor',
        ),
        migrations.RemoveField(
            model_name='ssd',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='ssd',
            name='market_launch_date',
        ),
        migrations.RemoveField(
            model_name='ssd',
            name='thickness',
        ),
        migrations.RemoveField(
            model_name='videocards',
            name='base_gpu_frequency',
        ),
        migrations.RemoveField(
            model_name='videocards',
            name='card_height',
        ),
        migrations.RemoveField(
            model_name='videocards',
            name='card_length',
        ),
        migrations.RemoveField(
            model_name='videocards',
            name='cooling_system_thickness',
        ),
        migrations.RemoveField(
            model_name='videocards',
            name='directx_support',
        ),
        migrations.RemoveField(
            model_name='videocards',
            name='effective_memory_frequency',
        ),
        migrations.RemoveField(
            model_name='videocards',
            name='gpu',
        ),
        migrations.RemoveField(
            model_name='videocards',
            name='gpu_manufacturer',
        ),
        migrations.RemoveField(
            model_name='videocards',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='videocards',
            name='max_gpu_frequency',
        ),
        migrations.RemoveField(
            model_name='videocards',
            name='memory_bandwidth',
        ),
        migrations.RemoveField(
            model_name='videocards',
            name='memory_bus_width',
        ),
        migrations.RemoveField(
            model_name='videocards',
            name='number_of_stream_processors',
        ),
        migrations.RemoveField(
            model_name='videocards',
            name='power_connectors',
        ),
        migrations.RemoveField(
            model_name='videocards',
            name='recommended_power_supply',
        ),
        migrations.RemoveField(
            model_name='videocards',
            name='type_video_memory',
        ),
        migrations.RemoveField(
            model_name='videocards',
            name='video_memory',
        ),
        migrations.AddField(
            model_name='hdd',
            name='hardware_encryption',
            field=models.BooleanField(default=True, verbose_name='Аппаратное шифрование'),
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='audio_outputs',
            field=models.CharField(default=1, max_length=255, verbose_name='Аудио выходы(3.5мм jack)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='bluetooth',
            field=models.CharField(default=1, max_length=255, verbose_name='Bluetooth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='built_in_microphone',
            field=models.CharField(default=1, max_length=255, verbose_name='Встроенный микрофон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='built_in_speakers',
            field=models.CharField(default=1, max_length=255, verbose_name='Встроенные динамики'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='clock_frequency_cpu',
            field=models.CharField(default=1, max_length=255, verbose_name='Тактовая частота процессора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='configuration_drive_type',
            field=models.CharField(default=1, max_length=255, verbose_name='Конфигурация накопителя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='cpu_power_consumption',
            field=models.CharField(default=1, max_length=255, verbose_name='Энергопотребление процессора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='depth',
            field=models.CharField(default=1, max_length=255, verbose_name='Глубина'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='drive_capacity',
            field=models.CharField(default=1, max_length=255, verbose_name='Ёмкость накопителя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='energy_reserve',
            field=models.CharField(default=1, max_length=255, verbose_name='Запас энергии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='free_memory_slots',
            field=models.CharField(default=1, max_length=255, verbose_name='Свободных слотов памяти'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='graphics_card_feature',
            field=models.CharField(default=1, max_length=255, verbose_name='Характеристики видеокарты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='hdmi',
            field=models.CharField(default=1, max_length=255, verbose_name='HDMI'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='lan',
            field=models.CharField(default=1, max_length=255, verbose_name='LAN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='local_video_memory',
            field=models.CharField(default=1, max_length=255, verbose_name='Локальная видеопамять'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='matrix_frequency',
            field=models.CharField(default=1, max_length=255, verbose_name='Частота матрицы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='max_ram_memory',
            field=models.CharField(default=1, max_length=255, verbose_name='Максимальное кол-во оперативной памяти'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='mini_display_port',
            field=models.CharField(default=1, max_length=255, verbose_name='Mini display port'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='number_of_cores_cpu',
            field=models.CharField(default=1, max_length=255, verbose_name='Количество ядер процессора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='number_of_ssd_slots',
            field=models.CharField(default=1, max_length=255, verbose_name='Кол-во слотов для SSD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='number_of_threads_cpu',
            field=models.CharField(default=1, max_length=255, verbose_name='Количество потоков процессора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='ram_frequency',
            field=models.CharField(default=1, max_length=255, verbose_name='Частота оперативной памяти'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='ram_memory',
            field=models.CharField(default=1, max_length=255, verbose_name='Кол-во оперативной памяти'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='screen_diagonal',
            field=models.CharField(default=1, max_length=255, verbose_name='Диагональ дисплея'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='screen_resolution',
            field=models.CharField(default=1, max_length=255, verbose_name='Диагональ дисплея'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='thickness',
            field=models.CharField(default=1, max_length=255, verbose_name='Толщина'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='total_usb_2',
            field=models.CharField(default=1, max_length=255, verbose_name='Всего USB 2.0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='total_usb_type_a',
            field=models.CharField(default=1, max_length=255, verbose_name='Всего USB Type A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='total_usb_type_c',
            field=models.CharField(default=1, max_length=255, verbose_name='Всего USB Type C'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='turbo_frequency_cpu',
            field=models.CharField(default=1, max_length=255, verbose_name='Турбо частота процессора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='usb_4',
            field=models.CharField(default=1, max_length=255, verbose_name='USB4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='vga',
            field=models.CharField(default=1, max_length=255, verbose_name='VGA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='weight',
            field=models.CharField(default=1, max_length=255, verbose_name='Вес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='width',
            field=models.CharField(default=1, max_length=255, verbose_name='Ширина'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='wifi',
            field=models.CharField(default=1, max_length=255, verbose_name='Wi-Fi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphonetranslation',
            name='battery_capacity',
            field=models.CharField(default=1, max_length=255, verbose_name='Ёмкость аккумулятора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphonetranslation',
            name='built_in_camera',
            field=models.BooleanField(default=True, verbose_name='Встроенная камера'),
        ),
        migrations.AddField(
            model_name='smartphonetranslation',
            name='cpu_clock_speed',
            field=models.CharField(default=1, max_length=255, verbose_name='Тактовая частота процессора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphonetranslation',
            name='cpu_size',
            field=models.CharField(default=1, max_length=255, verbose_name='Разрядность процессора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphonetranslation',
            name='flash_memory',
            field=models.CharField(default=1, max_length=255, verbose_name='Флэш-память'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphonetranslation',
            name='front_camera',
            field=models.CharField(default=1, max_length=255, verbose_name='Фронтальная камера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphonetranslation',
            name='gpu_frequency',
            field=models.CharField(default=1, max_length=255, verbose_name='Частота ГПУ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphonetranslation',
            name='length',
            field=models.CharField(default=1, max_length=255, verbose_name='Длина'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphonetranslation',
            name='max_frames_per_second',
            field=models.CharField(default=1, max_length=255, verbose_name='Максимальное во-во кадров в секунду'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphonetranslation',
            name='max_video_resolution',
            field=models.CharField(default=1, max_length=255, verbose_name='Максимальное разрешение видео'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphonetranslation',
            name='num_of_cores',
            field=models.CharField(default=1, max_length=255, verbose_name='Кол-во ядер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphonetranslation',
            name='num_of_main_cam',
            field=models.CharField(default=1, max_length=255, verbose_name='Кол-во основных камер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphonetranslation',
            name='num_of_matrix_points',
            field=models.CharField(default=1, max_length=255, verbose_name='Кол-во точек матрицы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphonetranslation',
            name='num_of_screen_colors',
            field=models.CharField(default=1, max_length=255, verbose_name='Кол-во цветов экрана'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphonetranslation',
            name='num_of_sim_cards',
            field=models.CharField(default=1, max_length=255, verbose_name='Кол-во SIM-карт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphonetranslation',
            name='ram_mobile',
            field=models.CharField(default=1, max_length=255, verbose_name='Оперативная память'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphonetranslation',
            name='refresh_rate',
            field=models.CharField(default=1, max_length=255, verbose_name='Частота обновления экрана'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphonetranslation',
            name='screen_res',
            field=models.CharField(default=1, max_length=255, verbose_name='Разрешающая способность экрана'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphonetranslation',
            name='screen_resolution_mobile',
            field=models.CharField(default=1, max_length=255, verbose_name='Разрешение экрана'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphonetranslation',
            name='screen_size',
            field=models.CharField(default=1, max_length=255, verbose_name='Размер экрана'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphonetranslation',
            name='technical_process',
            field=models.CharField(default=1, max_length=255, verbose_name='Техпроцесс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphonetranslation',
            name='thickness',
            field=models.CharField(default=1, max_length=255, verbose_name='Толщина'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphonetranslation',
            name='width',
            field=models.CharField(default=1, max_length=255, verbose_name='Ширина'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='powersupplies',
            name='power_factor_correction',
            field=models.BooleanField(default=True, verbose_name='Коррекция фактора мощности (PFC)'),
        ),
        migrations.CreateModel(
            name='VideoCardsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=255, verbose_name='Интерфейс')),
                ('gpu_manufacturer', models.CharField(max_length=255, verbose_name='Производитель графического процессора')),
                ('gpu', models.CharField(max_length=255, verbose_name='Графический процессор')),
                ('base_gpu_frequency', models.CharField(max_length=255, verbose_name='Базовая частота графического процессора')),
                ('max_gpu_frequency', models.CharField(max_length=255, verbose_name='Максимальная частота графического процессора')),
                ('number_of_stream_processors', models.CharField(max_length=255, verbose_name='Количество потоковых процессоров')),
                ('video_memory', models.CharField(max_length=255, verbose_name='Видеопамять')),
                ('type_video_memory', models.CharField(max_length=255, verbose_name='Тип видеопамяти')),
                ('effective_memory_frequency', models.CharField(max_length=255, verbose_name='Эффективная частота памяти')),
                ('memory_bandwidth', models.CharField(max_length=255, verbose_name='Пропускная способность памяти')),
                ('memory_bus_width', models.CharField(max_length=255, verbose_name='Ширина шины памяти')),
                ('directx_support', models.CharField(max_length=255, verbose_name='Поддержка DirectX')),
                ('power_connectors', models.CharField(max_length=255, verbose_name='Разъемы питания')),
                ('recommended_power_supply', models.CharField(max_length=255, verbose_name='Рекомендуемый блок питания')),
                ('cooling_system_thickness', models.CharField(max_length=255, verbose_name='Толщина системы охлаждения')),
                ('card_length', models.CharField(max_length=255, verbose_name='Длина видеокарты')),
                ('card_height', models.CharField(max_length=255, verbose_name='Высота видеокарты ')),
                ('language', models.CharField(max_length=2, verbose_name='Выбор языка')),
                ('videocard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Storeapp.videocards')),
            ],
            options={
                'verbose_name': 'Видеокарты перевод ru - en',
                'verbose_name_plural': 'Видеокарты переводы ru - en',
            },
        ),
        migrations.CreateModel(
            name='SSDTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_launch_date', models.CharField(max_length=255, verbose_name='Дата выхода на рынок')),
                ('capacity', models.CharField(max_length=255, verbose_name='Объём')),
                ('form_factor', models.CharField(max_length=255, verbose_name='Форм-фактор')),
                ('interface', models.CharField(max_length=255, verbose_name='Интерфейс')),
                ('chip_type_flash', models.CharField(max_length=255, verbose_name='Тип микросхем Flash')),
                ('thickness', models.CharField(max_length=255, verbose_name='Толщина')),
                ('language', models.CharField(max_length=2, verbose_name='Выбор языка')),
                ('ssd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Storeapp.ssd')),
            ],
            options={
                'verbose_name': 'SSD перевод ru - en',
                'verbose_name_plural': 'SSD переводы ru - en',
            },
        ),
        migrations.CreateModel(
            name='RAMTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit', models.CharField(max_length=255, verbose_name='Набор')),
                ('capacity', models.CharField(max_length=255, verbose_name='Объем')),
                ('type', models.CharField(max_length=255, verbose_name='Тип памяти')),
                ('frequency', models.CharField(max_length=255, verbose_name='Частота')),
                ('pc_index', models.CharField(max_length=255, verbose_name='PC-индекс')),
                ('cas_latency', models.CharField(max_length=255, verbose_name='CAS Latency')),
                ('timings', models.CharField(max_length=255, verbose_name='Тайминги')),
                ('supply_voltage', models.CharField(max_length=255, verbose_name='Напряжение питания')),
                ('chip_location', models.CharField(max_length=255, verbose_name='Расположение чипов')),
                ('number_of_ranks', models.CharField(max_length=255, verbose_name='Количество ранков')),
                ('number_of_micro', models.CharField(max_length=255, verbose_name='Число микросхем')),
                ('capacity_of_micro', models.CharField(max_length=255, verbose_name='Ёмкость микросхем')),
                ('micro_type', models.CharField(max_length=255, verbose_name='Тип микросхем')),
                ('color', models.CharField(max_length=255, verbose_name='Подсветка элементов платы')),
                ('language', models.CharField(max_length=2, verbose_name='Выбор языка')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Storeapp.ram')),
            ],
            options={
                'verbose_name': 'Оперативная память перевод ru - en',
                'verbose_name_plural': 'Оперативная память переводы ru - en',
            },
        ),
        migrations.CreateModel(
            name='ProcessorsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_launch_date', models.CharField(max_length=255, verbose_name='Дата выхода на рынок')),
                ('the_lineup', models.CharField(max_length=255, verbose_name='Модельный ряд')),
                ('delivery_type', models.CharField(max_length=255, verbose_name='Тип поставки')),
                ('crystal_code_name', models.CharField(max_length=255, verbose_name='Кодовое название кристалла')),
                ('socket', models.CharField(max_length=255, verbose_name='Сокет')),
                ('number_of_cores', models.CharField(max_length=255, verbose_name='Количество ядер')),
                ('maximum_number_of_threads', models.CharField(max_length=255, verbose_name='Максимальное количество потоков')),
                ('base_clock_frequency', models.CharField(max_length=255, verbose_name='Базовая тактовая частота')),
                ('max_frequency', models.CharField(max_length=255, verbose_name='Максимальная частота')),
                ('cash_l2', models.CharField(max_length=255, verbose_name='Кэш L2')),
                ('cash_l3', models.CharField(max_length=255, verbose_name='Кэш L3')),
                ('memory_support', models.CharField(max_length=255, verbose_name='Поддержка памяти')),
                ('number_of_memory_channels', models.CharField(max_length=255, verbose_name='Количество каналов памяти')),
                ('max_memory_frequency', models.CharField(max_length=255, verbose_name='Макс. частота памяти')),
                ('type_gpu_express_controller', models.CharField(max_length=255, verbose_name='Тип встроенного контроллера PCI Express')),
                ('tdp', models.CharField(max_length=255, verbose_name='Расчетная тепловая мощность (TDP)')),
                ('technical_process', models.CharField(max_length=255, verbose_name='Техпроцесс')),
                ('language', models.CharField(max_length=2, verbose_name='Выбор языка')),
                ('processors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Storeapp.processors')),
            ],
            options={
                'verbose_name': 'Процессоры перевод ru - en',
                'verbose_name_plural': 'Процессоры переводы ru - en',
            },
        ),
        migrations.CreateModel(
            name='PowerSuppliesTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.CharField(max_length=255, verbose_name='Назначение')),
                ('power', models.CharField(max_length=255, verbose_name='Мощность')),
                ('power_supply_standard', models.CharField(max_length=255, verbose_name='Стандарт блока питания')),
                ('number_of_separate_lines_12v', models.CharField(max_length=255, verbose_name='Количество отдельных линий +12V')),
                ('max_line_current_12v', models.CharField(max_length=255, verbose_name='Макс. ток по линии +12V')),
                ('combined_load_12v', models.CharField(max_length=255, verbose_name='Комбинированная нагрузка по +12V')),
                ('efficiency', models.CharField(max_length=255, verbose_name='КПД')),
                ('power_supply_fan_size', models.CharField(max_length=255, verbose_name='Размер вентилятора блока питания')),
                ('total_fans', models.CharField(max_length=255, verbose_name='Количество вентиляторов')),
                ('power_cable_length', models.CharField(max_length=255, verbose_name='Длина кабеля питания')),
                ('motherboard_power', models.CharField(max_length=255, verbose_name='Питание материнской платы')),
                ('height', models.CharField(max_length=255, verbose_name='Высота')),
                ('width', models.CharField(max_length=255, verbose_name='Ширина')),
                ('depth', models.CharField(max_length=255, verbose_name='Глубина')),
                ('language', models.CharField(max_length=2, verbose_name='Выбор языка')),
                ('power_supplies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Storeapp.powersupplies')),
            ],
            options={
                'verbose_name': 'Блоки питания перевод ru - en',
                'verbose_name_plural': 'Блоки питания переводы ru - en',
            },
        ),
        migrations.CreateModel(
            name='MotherboardTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_launch_date', models.CharField(max_length=255, verbose_name='Дата выхода на рынок')),
                ('processor_support', models.CharField(max_length=255, verbose_name='Поддержка процессоров')),
                ('socket', models.CharField(max_length=255, verbose_name='Сокет')),
                ('chipset', models.CharField(max_length=255, verbose_name='Чипсет')),
                ('form_factor', models.CharField(max_length=255, verbose_name='Форм-фактор')),
                ('memory_type', models.CharField(max_length=255, verbose_name='Тип памяти')),
                ('number_of_memory_slots', models.CharField(max_length=255, verbose_name='Количество слотов памяти')),
                ('max_memory', models.CharField(max_length=255, verbose_name='Максимальный объём памяти')),
                ('memory_mode', models.CharField(max_length=255, verbose_name='Режим памяти')),
                ('max_memory_frequency', models.CharField(max_length=255, verbose_name='Максимальная частота памяти')),
                ('ver_pcl_express', models.CharField(max_length=255, verbose_name='Версия PCI Express')),
                ('total_pcl_express_x16', models.CharField(max_length=255, verbose_name='Количество PCI Express x16')),
                ('total_pcl_express_2_x16', models.CharField(max_length=255, verbose_name='Количество PCI Express 2.0 x16')),
                ('total_pcl_express_x1', models.CharField(max_length=255, verbose_name='Количество PCI Express x1')),
                ('total_pcl_express_2_x1', models.CharField(max_length=255, verbose_name='Количество PCI Express 2.0 x1')),
                ('total_pcl_express_2_x4', models.CharField(max_length=255, verbose_name='Количество PCI Express 2.0 x4')),
                ('total_pcl_express_2_x8', models.CharField(max_length=255, verbose_name='Количество PCI Express 2.0 x8')),
                ('total_m2', models.CharField(max_length=255, verbose_name='Количество ssd M.2')),
                ('total_sata_3', models.CharField(max_length=255, verbose_name='Количество SATA 3.0')),
                ('raid_info', models.CharField(max_length=255, verbose_name='RAID инфо')),
                ('built_in_sound_type', models.CharField(max_length=255, verbose_name='Встроенный звук тип')),
                ('sound_scheme', models.CharField(max_length=255, verbose_name='Звуковая схема')),
                ('total_usb_2', models.CharField(max_length=255, verbose_name='Количество USB 2.0')),
                ('total_usb_3_gen1_type_a_5gbit', models.CharField(max_length=255, verbose_name='Всего USB 3.2 Gen1 Type-A (5 Гбит/с)')),
                ('total_usb_3_gen2_type_a_10gbit', models.CharField(max_length=255, verbose_name='Всего USB 3.2 Gen2 Type-A (10 Гбит/с)')),
                ('total_usb_3_gen1_type_c_5gbit', models.CharField(max_length=255, verbose_name='Всего USB 3.2 Gen1 Type-C (5 Гбит/с)')),
                ('total_usb_3_gen2_type_c_10gbit', models.CharField(max_length=255, verbose_name='Всего USB 3.2 Gen2 Type-C (10 Гбит/с)')),
                ('total_audio_jack', models.CharField(max_length=255, verbose_name='Всего аудио (3.5 мм jack)')),
                ('total_ps_2', models.CharField(max_length=255, verbose_name='Всего PS/2')),
                ('total_hdmi', models.CharField(max_length=255, verbose_name='Всего HDMI')),
                ('total_cpu_fan_connectors', models.CharField(max_length=255, verbose_name='Всего разъемов для вентилятора ЦП')),
                ('total_sockets_for_cbo_processor', models.CharField(max_length=255, verbose_name='Всего разъемов для СВО процессора')),
                ('total_case_fan_connectors', models.CharField(max_length=255, verbose_name='Всего разъемов для корпусных вентиляторов')),
                ('total_5v_argb_lighting_connectors', models.CharField(max_length=255, verbose_name='Всего разъемов для подсветки ARGB 5В')),
                ('total_12v_lighting_connectors', models.CharField(max_length=255, verbose_name='Всего разъемов для подсветки RGB 12В')),
                ('language', models.CharField(max_length=2, verbose_name='Выбор языка')),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Storeapp.motherboard')),
            ],
            options={
                'verbose_name': 'Материнские платы перевод ru - en',
                'verbose_name_plural': 'Материнские платы переводы ru - en',
            },
        ),
        migrations.CreateModel(
            name='HDDTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_type', models.CharField(max_length=255, verbose_name='Тип накопителя')),
                ('capacity', models.CharField(max_length=255, verbose_name='Объём')),
                ('form_factor', models.CharField(max_length=255, verbose_name='Форм-фактор')),
                ('interface', models.CharField(max_length=255, verbose_name='Интерфейс')),
                ('spindle_speed', models.CharField(max_length=255, verbose_name='Скорость вращения шпинделя')),
                ('buffer', models.CharField(max_length=255, verbose_name='Буфер')),
                ('sector_size', models.CharField(max_length=255, verbose_name='Размер сектора')),
                ('sequential_read_speed', models.CharField(max_length=255, verbose_name='Скорость последовательного чтения')),
                ('read_write_noise', models.CharField(max_length=255, verbose_name='Уровень шума при чтении/записи')),
                ('standby_noise', models.CharField(max_length=255, verbose_name='Уровень шума в режиме ожидания')),
                ('shock_during_operation', models.CharField(max_length=255, verbose_name='Ударная нагрузка при работе')),
                ('non_operation_shock', models.CharField(max_length=255, verbose_name='Ударная нагрузка в нерабочем состоянии')),
                ('power_consumption_1', models.CharField(max_length=255, verbose_name='Энергопотребление (чтение/запись)')),
                ('power_consumption_2', models.CharField(max_length=255, verbose_name='Энергопотребление (ожидание)')),
                ('time_between_failures', models.CharField(max_length=255, verbose_name='Время наработки на отказ (МТBF)')),
                ('thickness', models.CharField(max_length=255, verbose_name='Толщина')),
                ('language', models.CharField(max_length=2, verbose_name='Выбор языка')),
                ('hdd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Storeapp.hdd')),
            ],
            options={
                'verbose_name': 'HDD перевод ru - en',
                'verbose_name_plural': 'HDD переводы ru - en ',
            },
        ),
        migrations.CreateModel(
            name='CoolersTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Тип')),
                ('cooling_type', models.CharField(max_length=255, verbose_name='Тип охлаждения')),
                ('socket', models.CharField(max_length=255, verbose_name='Сокет')),
                ('power_dissipation', models.CharField(max_length=255, verbose_name='Рассеиваемая мощность')),
                ('radiator_metal', models.CharField(max_length=255, verbose_name='Материал радиатора')),
                ('total_heat_pipes', models.CharField(max_length=255, verbose_name='Всего тепловых трубок')),
                ('fan_diameter', models.CharField(max_length=255, verbose_name='Диаметр вентилятора')),
                ('total_fans', models.CharField(max_length=255, verbose_name='Количество вентиляторов')),
                ('bearing', models.CharField(max_length=255, verbose_name='Подшипник')),
                ('max_rotation_speed', models.CharField(max_length=255, verbose_name='Максимальная скорость вращения')),
                ('connection_type', models.CharField(max_length=255, verbose_name='Тип подключения')),
                ('noise_lvl', models.CharField(max_length=255, verbose_name='Уровень шума')),
                ('width', models.CharField(max_length=255, verbose_name='Ширина')),
                ('depth', models.CharField(max_length=255, verbose_name='Глубина')),
                ('height', models.CharField(max_length=255, verbose_name='Высота')),
                ('weight', models.CharField(max_length=255, verbose_name='Вес')),
                ('language', models.CharField(max_length=2, verbose_name='Выбор языка')),
                ('coolers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Storeapp.coolers')),
            ],
            options={
                'verbose_name': 'Системы охлаждения перевод ru - en',
                'verbose_name_plural': 'Системы охлаждения переводы ru - en',
            },
        ),
        migrations.CreateModel(
            name='CaseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_supply', models.CharField(max_length=255, verbose_name='Блок питания')),
                ('type_of_case', models.CharField(max_length=255, verbose_name='Тип корпуса')),
                ('case_color', models.CharField(max_length=255, verbose_name='Цвет корпуса')),
                ('case_material', models.CharField(max_length=255, verbose_name='Материал корпуса')),
                ('window_material', models.CharField(max_length=255, verbose_name='Материал окна')),
                ('max_motherboard_size', models.CharField(max_length=255, verbose_name='Макс.размер материнской платы')),
                ('compatible_motherboard', models.CharField(max_length=255, verbose_name='Совместимые материнские платы')),
                ('power_supply_loc', models.CharField(max_length=255, verbose_name='Расположение блока питания')),
                ('number_of_places_for_fans', models.CharField(max_length=255, verbose_name='Количество мест для вентиляторов')),
                ('installed_coolers', models.CharField(max_length=255, verbose_name='Установленные кулеры')),
                ('cooler_illumination_color', models.CharField(max_length=255, verbose_name='Цвет подсветки кулера')),
                ('expansion_slots', models.CharField(max_length=255, verbose_name='Слоты расширения')),
                ('max_video_card_length', models.CharField(max_length=255, verbose_name='Макс.длина видеокарты')),
                ('max_cpu_cooler_height', models.CharField(max_length=255, verbose_name='Макс.высота процессорного кулера')),
                ('height', models.CharField(max_length=255, verbose_name='Высота')),
                ('width', models.CharField(max_length=255, verbose_name='Ширина')),
                ('depth', models.CharField(max_length=255, verbose_name='Глубина')),
                ('weight', models.CharField(max_length=255, verbose_name='Вес')),
                ('language', models.CharField(max_length=2, verbose_name='Выбор языка')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Storeapp.case')),
            ],
            options={
                'verbose_name': 'Корпуса перевод ru - en',
                'verbose_name_plural': 'Корпуса переводы ru - en',
            },
        ),
    ]
