# Generated by Django 3.2.6 on 2021-09-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storeapp', '0007_auto_20210913_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coolers',
            options={'verbose_name': 'Система охлаждения', 'verbose_name_plural': 'Системы охлаждения'},
        ),
        migrations.AlterModelOptions(
            name='tabicons',
            options={'verbose_name': 'Дополнительная информация', 'verbose_name_plural': 'Дополнительная информация'},
        ),
        migrations.AlterField(
            model_name='smartphonetranslation',
            name='audio_output_mobile',
            field=models.CharField(max_length=255, verbose_name='Аудиовыход'),
        ),
        migrations.AlterField(
            model_name='smartphonetranslation',
            name='battery_type',
            field=models.CharField(max_length=255, verbose_name='Тип аккумулятора'),
        ),
        migrations.AlterField(
            model_name='smartphonetranslation',
            name='bluetooth_mobile',
            field=models.CharField(max_length=255, verbose_name='Bluetooth'),
        ),
        migrations.AlterField(
            model_name='smartphonetranslation',
            name='body_color',
            field=models.CharField(max_length=255, verbose_name='Цвет корпуса'),
        ),
        migrations.AlterField(
            model_name='smartphonetranslation',
            name='body_design',
            field=models.CharField(max_length=255, verbose_name='Конструкция корпуса'),
        ),
        migrations.AlterField(
            model_name='smartphonetranslation',
            name='body_material',
            field=models.CharField(max_length=255, verbose_name='Материал корпуса'),
        ),
        migrations.AlterField(
            model_name='smartphonetranslation',
            name='built_in_camera',
            field=models.CharField(max_length=255, verbose_name='Встроенная камера'),
        ),
        migrations.AlterField(
            model_name='smartphonetranslation',
            name='front_panel_color',
            field=models.CharField(max_length=255, verbose_name='Цвет фронтальной панели'),
        ),
        migrations.AlterField(
            model_name='smartphonetranslation',
            name='microusb_connector',
            field=models.CharField(max_length=255, verbose_name='Разьем подключения microUSB 2.0'),
        ),
        migrations.AlterField(
            model_name='smartphonetranslation',
            name='mobile_operation_system',
            field=models.CharField(max_length=255, verbose_name='Операционная система'),
        ),
        migrations.AlterField(
            model_name='smartphonetranslation',
            name='platform',
            field=models.CharField(max_length=255, verbose_name='Платформа'),
        ),
        migrations.AlterField(
            model_name='smartphonetranslation',
            name='screen_technology',
            field=models.CharField(max_length=255, verbose_name='Технология экрана'),
        ),
        migrations.AlterField(
            model_name='smartphonetranslation',
            name='sim_card_format',
            field=models.CharField(max_length=255, verbose_name='Формат SIM-карт'),
        ),
        migrations.AlterField(
            model_name='smartphonetranslation',
            name='ver_mobile_operation_system',
            field=models.CharField(max_length=255, verbose_name='Версия операционной системы'),
        ),
        migrations.AlterField(
            model_name='smartphonetranslation',
            name='wifi_mobile',
            field=models.CharField(max_length=255, verbose_name='Wi-Fi'),
        ),
    ]
