# Generated by Django 3.2.6 on 2021-09-15 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Storeapp', '0008_auto_20210914_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notebooktranslation',
            options={'verbose_name': 'Ноутбук', 'verbose_name_plural': 'Ноутбуки'},
        ),
        migrations.RemoveField(
            model_name='notebooktranslation',
            name='notebook',
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='camera',
            field=models.BooleanField(default=True, verbose_name='Камера'),
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Storeapp.category', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='charge_via_usb_type_c',
            field=models.BooleanField(default=True, verbose_name='Зарядка ноутбука через USB Type C'),
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='description',
            field=models.TextField(max_length=5000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='discrete_graphics',
            field=models.BooleanField(default=True, verbose_name='Дискретная видеокарта'),
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='fast_charging',
            field=models.BooleanField(default=True, verbose_name='Быстрая зарядка'),
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='image',
            field=models.ImageField(default=1, upload_to='web_media/products/', verbose_name='Изображение товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='multimedia_touchpad',
            field=models.BooleanField(default=True, verbose_name='Мультимедийная сенсорная панель'),
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Наименование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebooktranslation',
            name='usb_c_power_adapter',
            field=models.BooleanField(default=True, verbose_name='Адаптер питания USB Type C'),
        ),
        migrations.DeleteModel(
            name='Notebook',
        ),
    ]
