# Generated by Django 3.2.6 on 2021-10-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storeapp', '0011_auto_20211004_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=255, verbose_name='Тема')),
                ('title', models.CharField(max_length=1024, verbose_name='Описание')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Последнее обновление',
                'verbose_name_plural': 'Последние обновления',
            },
        ),
    ]
